---
- name: Create multiple users and copy files into users home dirs
  hosts: all
  tasks:
    - name: Create users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: Raja,b: intelliqit,c: /tmp/Raja}
        - {a: Rani,b: intelliqit,c: /home/Rani}
    - name: Copy files into users home dir
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd,b: /tmp/Raja}
        - {a: /etc/group,b: /home/Rani}
...
